### ISSUE TITLE
v1.0.1 Release Checklist

### ISSUE THREAD

**Issue by hershpa** [intel/intel-technology-enabling-for-openshift#105]
### **v1.0.1 Release Checklist**

- Minor release adding support for QAT on OCP 4.12.26+. QAT firmware integrated on 4.12.26.

- [x] Receive 0.26.2 release from Intel Device Plugins #https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1497
- [x] Review NFD configuration for QAT https://github.com/intel/intel-technology-enabling-for-openshift/pull/112
- [x] Update Documentation
- [x] Machine Configuration for QAT
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1506
- [x] Release driver 1.1.0 here https://github.com/intel/intel-data-center-gpu-driver-for-openshift
- [x] Cut the release
- [x] https://github.com/intel/intel-technology-enabling-for-openshift/issues/122
