### ISSUE TITLE
v1.1.0 Release Checklist

### ISSUE THREAD

**Issue by hershpa** [intel/intel-technology-enabling-for-openshift#114]
### **`v1.1.0` Release Checklist**

- Adding support for OCP `4.13.10+`

- [x] Decide upstream version of Intel Device Plugins. Current leading candidate is `v0.28.0`
- [x] Move to UBI 9 based images for all plugin, init-container and GPU driver container images
- [x] Release GPU driver version `2.0.0` for OpenShift here https://github.com/intel/intel-data-center-gpu-driver-for-openshift
- [x] Review SELinux requirements and if any patches needed in container-selinux project.
- [x] Review NFD configuration and add node feature rules.
- [x] Review KMM configuration, Module CR updates, for KMM version `1.1.1`
- [x] Machine Configuration
- [x] Build init-container and plugin images
- [x] Build operator bundle and operator image
- [x] Update libraries, images to ubi9 and verify SGX, QAT, GPU workloads 
- [x] Update Documentation
- [x] Cut the release

**Comment by mythi** [comment]
>  Decide upstream version of Intel Device Plugins

my proposal is to go with v0.28 to catch up the development cycle

> Build init container and plugin images

and drop SGX and GPU initcontainers

> Build operator bundle and operator image

a must-have requirement is to move to "seamless upgrade" with v0.28

**Comment by chaitanya1731** [comment]
@mythi  quick question.. Since OCP version 4.13.10 currently has NFD version 4.13, and the majority of the changes in version 0.28.0 are designed for NFD 4.14, how can we ensure compatibility between version 0.28.0 and OCP 4.13.10? Should we continue to rely on initcontainers as a workaround due to the absence of NFD 4.14 in OCP 4.13.10?
