### ISSUE TITLE
Task Checking List for 1.0.0 Release

### ISSUE THREAD

**Issue by uMartinXu** [intel/intel-technology-enabling-for-openshift#14]
# Summary 
This issue is used to track the tasks that need to be finished in 1.0.0  release.

# Task List
- [x] Code cleaning up

- [x] [OCP 4.12 does not support launching SGX enclaves ](https://issues.redhat.com/browse/OCPBUGS-8435)

- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1377
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1390
- [x] Publishing of Intel Data Center GPU Driver Images for OperShift-4.12.x
- [x] https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/33

**Comment by uMartinXu** [comment]
for issue https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1377 for 1.0.0 GA release, we will add the detailed instructions in the related release documents to clarify what are the supported options. And we will continue to work with intel device plugin for kubernetes upstream on the final solution for the future release.
