### ISSUE TITLE
v1.2.0 Release Checklist for RHOCP 4.14.x

### ISSUE THREAD

**Issue by hershpa** [intel/intel-technology-enabling-for-openshift#188]
### **About `v1.2.0` Release**
1.2.0 release is the maintenance release for OCP 4.14.x.

- In this maintenance release, we intend to cut a quick release and make sure all the existing key features continue working properly on the new OCP y release. 
- We will not introduce any major change including the major components upgrading and complicated bug fixing.
- None of the new features will be added into the maintenance release.
- The Maintenance release will rely on the CI/CD Pipeline to make sure the project comply with the OpenShift Operator Aggressive mode, which means the Operator released on the old Openshift version by default should continue work on the new OpenShift release      
 
### **`v1.2.0` Release Checklist**
- [x] https://github.com/intel/intel-technology-enabling-for-openshift/issues/113
- [x] https://github.com/intel/intel-technology-enabling-for-openshift/issues/107
- [ ] Regression Testing using CI/CD Pipeline(if the Pipeline is ready to use) _as of 2/23/24- pipeline not yet a part of 1.2.0 release_
- [x] Quick bug fixing if needed- (not a bug-for SGX + NFD rule not updated in 1.2.0, will be added to release 1.2.1)
- [x] Update Documentation
- [x] Cut the release
- [x] https://github.com/intel/intel-technology-enabling-for-openshift/issues/194
