### ISSUE TITLE
v1.2.1 Release Checklist

### ISSUE THREAD

**Issue by vbedida79** [intel/intel-technology-enabling-for-openshift#219]
### **`v1.2.1` Release**
- 1.2.1 release is GA for OCP 4.14.11
- Support for Intel Data Center GPU Max Series 
- All features verified from previous release- will be supported
- Upgrades and major bug fixes- if any
 
### **Release Checklist**
- [x] Machine Configs for GPU review- _(Reboot free GPU provisioning supported, MCO no longer used)_
- [x] KMM review
- [x] NFD review (for SGX and NFR)
- [x] Plugin images and changes
- [x] https://github.com/intel/intel-technology-enabling-for-openshift/issues/214
- [x] Update tests
- [x] Build operator bundle and certify- if needed
- [x] Update Documentation, readmes, release table
- [x] Cut the release
