### ISSUE TITLE
v1.3.0 Release Checklist

### ISSUE THREAD

**Issue by vbedida79** [intel/intel-technology-enabling-for-openshift#249]
### **`v1.3.0` Release**
- 1.3.0 release is GA for OCP 4.15.15
- Intel GPU Media driver support
- Intel device plugins 0.29.0 version
- Support for SGX EPC resource without init container of device plugins 0.29.0 version- using NFD's NodeFeatureRule instance
- All features verified from previous release- will be supported
- Upgrades and major bug fixes- if any
 
### **Release Checklist**
- [x] KMM module CR verification
- [x] GPU Media driver review- (prereq/yaml changes, tests, readmes)
- [x] Intel device plugins 0.29.0 (verify updates, https://github.com/intel/intel-technology-enabling-for-openshift/issues/255)
- [x] NFD review (SGX EPC resource without init container  via NFD's NodeFeatureRule instance)
- [x] Plugin images and changes
- [x] Update tests (SGX SDK 2.24, GPU, QAT- if any)
- [x] Build operator bundle and certify
- [x] Update Documentation, readmes, release table
- [x] Create release branch- _release-v1.3.0_ (make related links/readme changes with this branch)
- [x] Cut the release and Publish 1.3.0 documentation
