### ISSUE TITLE
Upstream & OCP Tasks Tracking List

### ISSUE THREAD

**Issue by uMartinXu** [intel/intel-technology-enabling-for-openshift#28]
### Summary
This issue is used as the tracking List used by us to track the issues or tasks filed in the other projects.  After we triage and root cause some bugs, new features or enhancement to a specific project, we will file an issue in that project, and then just add one item into the checklist to track the upstream or OCP issues and tasks. And then we will resolve these issues with the specific upstream project to finish the tasks one by one in upstream and downstream to OCP.

### Issue & Task List
- [ ] https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/29
- [x] #92
- [ ] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1377
- [ ] [Support for accelerators (include Intel Data Center GPU) via OdhDashboardConfig in ODH and OCP](https://github.com/opendatahub-io/odh-dashboard/issues/956)
- [x] https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/33
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1416
- [ ] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1401
- [ ] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1408
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1506
- [x] qatlib package missing in UBI 8, unable to dnf install: https://connect.redhat.com/support/technology-partner/#/case/03601299
- [ ] long term solution for load vfio-pci driver for QAT
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1529 
- [x] https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1528
- [x] https://github.com/containers/container-selinux/issues/269

**Comment by uMartinXu** [comment]
> I'd suggest to use `Projects` but it's up to you
Thanks for your reminder. 
Just noticed that Github has this project feature for people to manage the project tasks. :-)

However
This tracking List is only used by us to track the issues or tasks filed in the other projects. You know after we triage and root cause some bugs to a specific project, we will file an issue in that project, and then just add one item to the checklist.  So we can track all the upstream or OCP issues and tasks we care about very easily.
