### ISSUE TITLE
v1.3.1 Release checklist

### ISSUE THREAD

**Issue by vbedida79** [intel/intel-technology-enabling-for-openshift#281]
v1.3.1 Release

- 1.3.1 prototype release for OCP 4.14
- OPEA chatqna initial prototype workload setup with rhoai (readme and tgi serving runtime)
- Gaudi accelerator setup pipeline on OCP (ansible playbook)

Release Checklist
 
- [x] OPEA chatqna initial prototype workload with rhoai verification (based on https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/deprecated)
- [x] Gaudi accelerator setup readme
- [x] Gaudi accelerator setup pipeline on OCP (ansible playbook yaml and readme)
- [x] chatqna workload readme- (initial high level setup, tgi serving runtime yaml and rhoai instructions)
- [x]  Documentation readme updates for 1.3.1 (4.15 change to 4.14, links etc)
- [x] Add1.3.1 to release table
- [x] Cut release and publish documentation
