### ISSUE TITLE
v1.4.0 Release checklist

### ISSUE THREAD

**Issue by vbedida79** [intel/intel-technology-enabling-for-openshift#302]
v1.4.0 Release

- Prototype release for OCP 4.16
- DSA feature for Intel device plugins operator

Release Checklist

- [x] DSA for NFD, MCO
- [x] Plugin images
- [x] Add DSA layer 2 test
- [x]  Verify SGX, QAT
- [x] Build operator bundle and certify
- [x] Update Documentation, readmes
- [x] Create release branch- release-v1.4.0 (make related links/readme changes with this branch)
- [x] Add 1.4.0 to release table
- [x] Cut the release and Publish 1.4.0 documentation
